
# This file describes the alternative machine learning models
# available to InvokeAI script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
__metadata__:
  version: 3.0.0
sd-1/main/Dungeons-and-Diffusion:
  path: sd-1/main/Dungeons-and-Diffusion
  description: Dungeons & Dragons characters (2.13 GB)
  variant: normal
  format: diffusers
sd-1/main/openjourney:
  path: sd-1/main/openjourney
  description: An SD 1.5 model fine tuned on Midjourney; prompt with "mdjrny-v4 style"
    (2.13 GB)
  variant: normal
  format: diffusers
sd-2/main/stable-diffusion-2-inpainting:
  path: sd-2/main/stable-diffusion-2-inpainting
  description: Stable Diffusion version 2.0 inpainting model (5.21 GB)
  variant: inpaint
  format: diffusers
sd-1/main/dreamlike-photoreal-2:
  path: sd-1/main/dreamlike-photoreal-2
  description: A photorealistic model trained on 768 pixel images based on SD 1.5
    (2.13 GB)
  variant: normal
  format: diffusers
sd-1/main/trinart_stable_diffusion_v2:
  path: sd-1/main/trinart_stable_diffusion_v2
  description: An SD-1.5 model finetuned with ~40K assorted high resolution manga/anime-style
    images (2.13 GB)
  variant: normal
  format: diffusers
sd-1/main/Inkpunk-Diffusion:
  path: sd-1/main/Inkpunk-Diffusion
  description: Stylized illustrations inspired by Gorillaz, FLCL and Shinkawa; prompt
    with "nvinkpunk" (4.27 GB)
  variant: normal
  format: diffusers
sd-1/main/seek.art_MEGA:
  path: sd-1/main/seek.art_MEGA
  description: A general use SD-1.5 "anything" model that supports multiple styles
    (2.1 GB)
  variant: normal
  format: diffusers
sd-1/main/Analog-Diffusion:
  path: sd-1/main/Analog-Diffusion
  description: An SD-1.5 model trained on diverse analog photographs (2.13 GB)
  variant: normal
  format: diffusers
sd-1/main/stable-diffusion-v1-5:
  path: sd-1/main/stable-diffusion-v1-5
  description: Stable Diffusion version 1.5 diffusers model (4.27 GB)
  variant: normal
  format: diffusers
sdxl-refiner/main/stable-diffusion-xl-refiner-1-0:
  path: sdxl-refiner/main/stable-diffusion-xl-refiner-1-0
  description: Stable Diffusion XL refiner model (12 GB)
  variant: normal
  format: diffusers
sd-2/main/stable-diffusion-2-1:
  path: sd-2/main/stable-diffusion-2-1
  description: Stable Diffusion version 2.1 diffusers model, trained on 768 pixel
    images (5.21 GB)
  variant: normal
  format: diffusers
sdxl/main/stable-diffusion-xl-base-1-0:
  path: sdxl/main/stable-diffusion-xl-base-1-0
  description: Stable Diffusion XL base model (12 GB)
  variant: normal
  format: diffusers
sd-1/main/stable-diffusion-v1-5-inpainting:
  path: sd-1/main/stable-diffusion-v1-5-inpainting
  description: RunwayML SD 1.5 model optimized for inpainting, diffusers version (4.27
    GB)
  variant: inpaint
  format: diffusers
sd-1/ip_adapter/ip_adapter_sd15:
  path: sd-1/ip_adapter/ip_adapter_sd15
  description: IP-Adapter for SD 1.5 models
  format: invokeai
sd-1/ip_adapter/ip_adapter_plus_face_sd15:
  path: sd-1/ip_adapter/ip_adapter_plus_face_sd15
  description: Refined IP-Adapter for SD 1.5 models, adapted for faces
  format: invokeai
sd-1/ip_adapter/ip_adapter_plus_sd15:
  path: sd-1/ip_adapter/ip_adapter_plus_sd15
  description: Refined IP-Adapter for SD 1.5 models
  format: invokeai
sdxl/ip_adapter/ip_adapter_sdxl:
  path: sdxl/ip_adapter/ip_adapter_sdxl
  description: IP-Adapter for SDXL models
  format: invokeai
any/clip_vision/ip_adapter_sd_image_encoder:
  path: any/clip_vision/ip_adapter_sd_image_encoder
  description: Required model for using IP-Adapters with SD-1/2 models
  format: diffusers
any/clip_vision/ip_adapter_sdxl_image_encoder:
  path: any/clip_vision/ip_adapter_sdxl_image_encoder
  description: Required model for using IP-Adapters with SDXL models
  format: diffusers
sd-1/main/Deliberate_v5:
  path: sd-1/main/Deliberate_v5
  description: Versatile model that produces detailed images up to 768px (4.27 GB)
  variant: normal
  format: diffusers
sd-1/main/dreamshaper_v8:
  path: sd-1/main/dreamshaper_v8
  description: sd-1 main model dreamshaper_v8
  variant: normal
  format: diffusers
sd-1/main/dreamshaper_v8_Inpainting:
  path: sd-1/main/dreamshaper_v8_Inpainting
  description: sd-1 main model dreamshaper_v8_Inpainting
  variant: inpaint
  format: diffusers
sd-1/main/majicmixRealistic_v7:
  path: sd-1/main/majicmixRealistic_v7
  description: sd-1 main model majicmixRealistic_v7
  variant: normal
  format: diffusers
sd-1/main/majicmixRealistic_v7_inpainting:
  path: sd-1/main/majicmixRealistic_v7_inpainting
  description: sd-1 main model majicmixRealistic_v7_inpainting
  variant: inpaint
  format: diffusers
sd-1/lora/add_detail:
  path: /mnt/w/Code/AIGC/invokeai/autoimport/lora/add_detail.safetensors
  description: sd-1 lora model add_detail
  format: lycoris
sdxl/lora/add_detail_xl:
  path: /mnt/w/Code/AIGC/invokeai/autoimport/lora/add_detail_xl.safetensors
  description: sdxl lora model add_detail_xl
  format: lycoris
sd-1/lora/Ink_scenery:
  path: sd-1/lora/Ink_scenery.safetensors
  format: lycoris
sd-2/lora/shojovibe_v11:
  path: /mnt/w/Code/AIGC/invokeai/autoimport/lora/shojovibe_v11.safetensors
  description: sd-2 lora model shojovibe_v11
  format: lycoris
